name:                tdlib-haskell-bindings
version:             0.1.0.0
github:              "egormkn/tdlib-haskell-bindings"
license:             WTFPL
author:              "Nufeen"
maintainer:          "darwin@email.su"
copyright:           "Nufeen"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Haskell bindings for Telegram Database Library
category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/egormkn/tdlib-haskell-bindings#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - aeson
  - bytestring
  - text
  extra-libraries: tdjson

executables:
  tdlib-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tdlib-haskell-bindings

tests:
  tdlib-haskell-bindings-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tdlib-haskell-bindings
